# Generated by Django 5.0 on 2023-12-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
